default_agent: teachers_assistant
agents:
  teachers_assistant:
    name: teachers_assistant
    entrypoint: teachers_assistant.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::339713026409:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-2ad1693c69
      execution_role_auto_create: false
      account: '339713026409'
      region: us-west-2
      ecr_repository: 339713026409.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-teachers_assistant
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: teachers_assistant-HVUKwrBAa5
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:339713026409:runtime/teachers_assistant-HVUKwrBAa5
      agent_session_id: 3f77bdcc-4d21-46ce-91d4-9d5437ebe479
    codebuild:
      project_name: bedrock-agentcore-teachers_assistant-builder
      execution_role: arn:aws:iam::339713026409:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-2ad1693c69
      source_bucket: bedrock-agentcore-codebuild-sources-339713026409-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
